parent: !include default.yaml
robot_interface:
  body:
    plugin: SendFollowJointTrajectory
    namespace: /whole_body_controller/body/follow_joint_trajectory
    state_topic: /whole_body_controller/body/state
    fill_velocity_values: False
general_options:
  joint_weights:
    # the planner prefers low weight joints to achieve solutions
    # higher weights reduce wiggling, but lower the maximum joint velocity, which might make the planner stop too early
    velocity:
      default: 0.001
      override: {}
    acceleration:
      default: 0
      override: { }
    jerk:
      default: 0.001
      override: { }
#    snap:
#      default: 0
#      override: { }
  joint_limits: # giskard will use the min of this number and limits from the urdf
    velocity:
      linear: # m/s
        default: 1
        override: {}
      angular: # rad/s
        default: 1
        override: {}
    acceleration:
      linear: # m/s**2
        default: 1e3
        override: { }
      angular: # rad/s**2
        default: 1e3
        override: { }
    jerk:
      linear: # m/s**3
        default: 30
        override: {}
      angular: # rad/s**3
        default: 30
        override: {}
#    snap:
#      linear: # m/s**4
#        default: 250
#        override: { }
#      angular: # rad/s**3
#        default: 250
#        override: { }
plugins:
  LoopDetector:
    precision: 4 # decimal places
collision_avoidance:
  external_collision_avoidance:
    default:
      hard_threshold: 0.0
      soft_threshold: 0.1
    override: {}
  self_collision_avoidance:
    ignore: [] # list pairs of links that should be removed from the self collision avoidance
    add: [ ] # list pairs of links that should be added to the self collision matrix
    number_of_repeller: 1 # each movable joint gets pushed away from the X objects closest to it
